version: '3.9'

networks:
  urlify-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/24

services:
  app:
    build:
      context: .
    ports:
      - "${APP_PORT:-8080}:8080"
    volumes:
      - .:/opt/app/urlify
    networks:
      - urlify-network
    depends_on:
      - postgres
      - migrator

  postgres:
    image: postgres:14-alpine
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./postgresql/data:/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    networks:
      - urlify-network

  migrator:
    image: migrate/migrate
    volumes:
      - ./database/migrations:/opt/app/urlify/database/migrations
    command: [ "-path", "/opt/app/urlify/database/migrations/", "-database",  "${DATABASE_DRIVER_NAME:-postgres}://${DB_USER}:${DB_PASSWORD}@${DATABASE_DRIVER_NAME:-postgres}:5432/${DB_NAME}?sslmode=disable", "up" ]
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - urlify-network
